### ISSUE TITLE
[ Bug ] 安装BetterNCM时微软报毒，特洛伊木马

### ISSUE THREAD

**Issue by Izayoi9** [std-microblock/chromatic#387]
### Bug 描述

在使用时发现网易云内显示BetterNCM新版本，于是点击更细按钮，随后网易云音乐闪退，windows安全中心报毒，并且光速隔离文件。然后再次打开网易云后发现变成原版网易云音乐，于是使用BetterNCM Installer再次安装，然而安装完成后又再次报毒。

### 复现步骤

1.打开betterncm_installer.exe
2.点击 安装

### 期望行为

修复此问题

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/105905446/daa75e79-d0f8-49f1-87af-ff5fdc230a34)
![image](https://github.com/MicroCBer/BetterNCM/assets/105905446/5bff2f1a-9347-46d5-88a4-b129849441c6)
![image](https://github.com/MicroCBer/BetterNCM/assets/105905446/284cac49-d402-4168-8950-73f790763a35)

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.8

### 网易云音乐 Patch 版本

1:b3c097c

**Comment by solstice23** [comment]
Duplicate of #386
