### ISSUE TITLE
[ Bug ] 疑似Windows Defender报毒

### ISSUE THREAD

**Issue by long45343** [std-microblock/chromatic#389]
### Bug 描述

Windows defender报毒了

### 复现步骤

安装后打开网易云Windows defender通知提示发现威胁

### 期望行为

解决此问题

### 屏幕截图

<img width="322" alt="image" src="https://github.com/MicroCBer/BetterNCM/assets/51872789/8a181420-dc1d-4742-acf1-97446971d3e9">

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2be876b

**Comment by solstice23** [comment]
Duplicate of #386

**Comment by MicroCBer** [comment]
可以试试最新测试通道是否报毒吗 这个我本地也无法复现

**Comment by long45343** [comment]
> 可以试试最新测试通道是否报毒吗 这个我本地也无法复现

现在扫描后没有发现有报毒现象，可能是随机事件/抽风？
我持续监测吧，有复现的时候我再发吧

**Comment by Reinhardt-L** [comment]
遇到同样的报毒，问题截图相同，一会试试beta看看情况

BetterNCM 版本
1.2.1

网易云音乐版本
2.10.10

网易云音乐 Patch 版本
ca5e0ab

**Comment by long45343** [comment]
> 最新的beta没有这个问题

Beta（1.2.1nightly）刚刚又出现了
<img width="547" alt="image" src="https://github.com/MicroCBer/BetterNCM/assets/51872789/b39f7b42-3888-430f-a61c-fc22fa5d9ad2">
BetterNCM 版本
1.2.1nightly

网易云音乐版本
2.10.10

网易云音乐 Patch 版本
2be876b

> 可以试试最新测试通道是否报毒吗 这个我本地也无法复现

刚刚又出现了

**Comment by long45343** [comment]
补充一下针对扫描的时候不会报毒，但是运行时有几率报毒
