### ISSUE TITLE
[ Bug ] GPU占用过高

### ISSUE THREAD

**Issue by Fyueg0** [std-microblock/chromatic#395]
### Bug 描述

听歌一会就占用非常高的cpu和gpu

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

减少占用

### 屏幕截图

<img width="517" alt="Snipaste_2023-06-09_20-18-56" src="https://github.com/MicroCBer/BetterNCM/assets/108653592/0449b38d-5ac4-4c10-883d-7b2c192d1ae3">

### BetterNCM 版本

1.2.1

### 网易云音乐版本

2.10.10

### 网易云音乐 Patch 版本

2be876b

### 补充

这个是数据
链接：https://pan.baidu.com/s/1Uf08iFgjP-_PYm2rF0CF2g?pwd=q230 
提取码：q230 
--来自百度网盘超级会员V5的分享

**Comment by seawave0564** [comment]
和apple music插件有关系

**Comment by MicroCBer** [comment]
插件问题，请在对应插件 Repo 下反馈
